//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETUP.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SETUP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap h1_posco1 {
            get {
                object obj = ResourceManager.GetObject("h1_posco1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Tension POR,10000.0
        ///Tension TR,50000.0
        ///Max Roll Force,1000.0
        ///Max Speed,600
        ///Work Roll Dia,68.0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string mill {
            get {
                return ResourceManager.GetString("mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap motif {
            get {
                object obj = ResourceManager.GetObject("motif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   204,29.1945,361.812,-261.7094,1471.2028,-3105.033,1789.1534
        ///301,29.1945,361.812,-261.7094,1471.2028,-3105.033,1789.1534
        ///301L,32.0719,732.866,-2480.6456,4643.5437,-4190.2834,1452.6633
        ///304,34.2615,563.0022,-1448.9489,2234.0748,-1663.7805,458.2273
        ///304J1,34.9584,423.7608,-1240.5824,2101.5325,-1569.735,408.887
        ///304L,23.539,414.83,-1253.6,2650,-2722.4,1042.3
        ///304N1,32.1992,591.5819,-1526.3331,2356.4071,-1758.824,485.9444
        ///304N2,34.83,867.7,-3386.32,6919.69,-6688.98,2434.87
        ///304CUW,34.9584,423.7608,-1240.5824,[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pp {
            get {
                return ResourceManager.GetString("pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6.0,15,14,14.5,10.5,10,10
        ///5.0,18,16,17,13,12,12.5
        ///4.0,20,19,19.5,14,13,13.5
        ///2.8,22,20,21,14.5,13.5,14
        ///1.5,24,23,23.5,15.5,15,15과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string r1maxrmean {
            get {
                return ResourceManager.GetString("r1maxrmean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.5,150,200,600,250과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   204,AUS,35
        ///301,AUS,35
        ///301L,AUS,35
        ///304,AUS,35
        ///304J1,AUS,35
        ///304L,AUS,35
        ///304N1,AUS,35
        ///304N2,AUS,35
        ///304CUW,AUS,35
        ///309SI,AUS,35
        ///310S,AUS,35
        ///316,AUS,35
        ///316L,AUS,35
        ///316TI,AUS,35
        ///321,AUS,35
        ///XM15J1,AUS,35
        ///409L,FER,30
        ///410L,FER,30
        ///429EM,FER,30
        ///430,FER,30
        ///430RE,FER,30
        ///430J1,FER,30
        ///430TI,FER,30
        ///436L,FER,30
        ///439,FER,30
        ///441,FER,30
        ///444,FER,30
        ///445NF,FER,30
        ///446M,FER,30
        ///470FC,FER,30
        ///410,MAR,30
        ///420J2,MAR,35과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUS,0.8,0.60
        ///FER,0.7,0.55
        ///MAR,0.75,0.58과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Thick2 {
            get {
                return ResourceManager.GetString("Thick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon zrm {
            get {
                object obj = ResourceManager.GetObject("zrm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
